version: 2
jobs:
  test:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run:
          name: "Set up environment"
          command: |
            echo "export PATH=$HOME/.composer/vendor/bin:$PATH" >> $BASH_ENV
            source /home/circleci/.bashrc
      - run:
          name: "Run PHP tests"
          command: |
            composer install
            composer test
      - run:
          name: "Run asset tests"
          command: |
            yarn
            yarn test
            yarn build

workflows:
  version: 2
  test:
    jobs:
      - test
